// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: IEntityRequest.cs.tt

namespace Microsoft.Graph
{
    using System;
    using System.IO;
    using System.Net.Http;
    using System.Threading;
    using System.Linq.Expressions;

    /// <summary>
    /// The interface IAttachmentBaseRequest.
    /// </summary>
    public partial interface IAttachmentBaseRequest : IBaseRequest
    {
        /// <summary>
        /// Creates the specified AttachmentBase using POST.
        /// </summary>
        /// <param name="attachmentBaseToCreate">The AttachmentBase to create.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The created AttachmentBase.</returns>
        System.Threading.Tasks.Task<AttachmentBase> CreateAsync(AttachmentBase attachmentBaseToCreate, CancellationToken cancellationToken = default);

        /// <summary>
        /// Creates the specified AttachmentBase using POST and returns a <see cref="GraphResponse{AttachmentBase}"/> object.
        /// </summary>
        /// <param name="attachmentBaseToCreate">The AttachmentBase to create.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The <see cref="GraphResponse{AttachmentBase}"/> object of the request.</returns>
        System.Threading.Tasks.Task<GraphResponse<AttachmentBase>> CreateResponseAsync(AttachmentBase attachmentBaseToCreate, CancellationToken cancellationToken = default);

        /// <summary>
        /// Deletes the specified AttachmentBase.
        /// </summary>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The task to await.</returns>
        System.Threading.Tasks.Task DeleteAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// Deletes the specified AttachmentBase and returns a <see cref="GraphResponse"/> object.
        /// </summary>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The task of <see cref="GraphResponse"/> to await.</returns>
        System.Threading.Tasks.Task<GraphResponse> DeleteResponseAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets the specified AttachmentBase.
        /// </summary>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The AttachmentBase.</returns>
        System.Threading.Tasks.Task<AttachmentBase> GetAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// Gets the specified AttachmentBase and returns a <see cref="GraphResponse{AttachmentBase}"/> object.
        /// </summary>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The <see cref="GraphResponse{AttachmentBase}"/> object of the request.</returns>
        System.Threading.Tasks.Task<GraphResponse<AttachmentBase>> GetResponseAsync(CancellationToken cancellationToken = default);

        /// <summary>
        /// Updates the specified AttachmentBase using PATCH.
        /// </summary>
        /// <param name="attachmentBaseToUpdate">The AttachmentBase to update.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <exception cref="ClientException">Thrown when an object returned in a response is used for updating an object in Microsoft Graph.</exception>
        /// <returns>The updated AttachmentBase.</returns>
        System.Threading.Tasks.Task<AttachmentBase> UpdateAsync(AttachmentBase attachmentBaseToUpdate, CancellationToken cancellationToken = default);

        /// <summary>
        /// Updates the specified AttachmentBase using PATCH and returns a <see cref="GraphResponse{AttachmentBase}"/> object.
        /// </summary>
        /// <param name="attachmentBaseToUpdate">The AttachmentBase to update.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <exception cref="ClientException">Thrown when an object returned in a response is used for updating an object in Microsoft Graph.</exception>
        /// <returns>The <see cref="GraphResponse{AttachmentBase}"/> object of the request.</returns>
        System.Threading.Tasks.Task<GraphResponse<AttachmentBase>> UpdateResponseAsync(AttachmentBase attachmentBaseToUpdate, CancellationToken cancellationToken = default);

        /// <summary>
        /// Updates the specified AttachmentBase using PUT.
        /// </summary>
        /// <param name="attachmentBaseToUpdate">The AttachmentBase object to update.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The task to await.</returns>
        System.Threading.Tasks.Task<AttachmentBase> PutAsync(AttachmentBase attachmentBaseToUpdate, CancellationToken cancellationToken = default);

        /// <summary>
        /// Updates the specified AttachmentBase using PUT and returns a <see cref="GraphResponse{AttachmentBase}"/> object.
        /// </summary>
        /// <param name="attachmentBaseToUpdate">The AttachmentBase object to update.</param>
        /// <param name="cancellationToken">The <see cref="CancellationToken"/> for the request.</param>
        /// <returns>The task of <see cref="GraphResponse{AttachmentBase}"/> to await.</returns>
        System.Threading.Tasks.Task<GraphResponse<AttachmentBase>> PutResponseAsync(AttachmentBase attachmentBaseToUpdate, CancellationToken cancellationToken = default);

        /// <summary>
        /// Adds the specified expand value to the request.
        /// </summary>
        /// <param name="value">The expand value.</param>
        /// <returns>The request object to send.</returns>
        IAttachmentBaseRequest Expand(string value);

        /// <summary>
        /// Adds the specified expand value to the request.
        /// </summary>
        /// <param name="expandExpression">The expression from which to calculate the expand value.</param>
        /// <returns>The request object to send.</returns>
        IAttachmentBaseRequest Expand(Expression<Func<AttachmentBase, object>> expandExpression);

        /// <summary>
        /// Adds the specified select value to the request.
        /// </summary>
        /// <param name="value">The select value.</param>
        /// <returns>The request object to send.</returns>
        IAttachmentBaseRequest Select(string value);

        /// <summary>
        /// Adds the specified select value to the request.
        /// </summary>
        /// <param name="selectExpression">The expression from which to calculate the select value.</param>
        /// <returns>The request object to send.</returns>
        IAttachmentBaseRequest Select(Expression<Func<AttachmentBase, object>> selectExpression);

    }
}
