// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: IEntityCollectionRequestBuilder.cs.tt
namespace Microsoft.Graph
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The interface ITodoTaskAttachmentsCollectionRequestBuilder.
    /// </summary>
    public partial interface ITodoTaskAttachmentsCollectionRequestBuilder : IBaseRequestBuilder
    {
        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <returns>The built request.</returns>
        ITodoTaskAttachmentsCollectionRequest Request();

        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <param name="options">The query and header options for the request.</param>
        /// <returns>The built request.</returns>
        ITodoTaskAttachmentsCollectionRequest Request(IEnumerable<Option> options);

        /// <summary>
        /// Gets an <see cref="IAttachmentBaseRequestBuilder"/> for the specified AttachmentBase.
        /// </summary>
        /// <param name="id">The ID for the AttachmentBase.</param>
        /// <returns>The <see cref="IAttachmentBaseRequestBuilder"/>.</returns>
        IAttachmentBaseRequestBuilder this[string id] { get; }

        /// <summary>
        /// Gets the request builder for AttachmentBaseCreateUploadSession.
        /// </summary>
        /// <returns>The <see cref="IAttachmentBaseCreateUploadSessionRequestBuilder"/>.</returns>
        IAttachmentBaseCreateUploadSessionRequestBuilder CreateUploadSession(
            AttachmentInfo attachmentInfo);
    }
}
