// ------------------------------------------------------------------------------
//  Copyright (c) Microsoft Corporation.  All Rights Reserved.  Licensed under the MIT License.  See License in the project root for license information.
// ------------------------------------------------------------------------------

// **NOTE** This file was generated by a tool and any changes will be overwritten.
// <auto-generated/>

// Template Source: EntityCollectionRequestBuilder.cs.tt
namespace Microsoft.Graph
{
    using System;
    using System.Collections.Generic;

    /// <summary>
    /// The type TodoTaskAttachmentsCollectionRequestBuilder.
    /// </summary>
    public partial class TodoTaskAttachmentsCollectionRequestBuilder : BaseRequestBuilder, ITodoTaskAttachmentsCollectionRequestBuilder
    {
        /// <summary>
        /// Constructs a new TodoTaskAttachmentsCollectionRequestBuilder.
        /// </summary>
        /// <param name="requestUrl">The URL for the built request.</param>
        /// <param name="client">The <see cref="IBaseClient"/> for handling requests.</param>
        public TodoTaskAttachmentsCollectionRequestBuilder(
            string requestUrl,
            IBaseClient client)
            : base(requestUrl, client)
        {
        }

        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <returns>The built request.</returns>
        public ITodoTaskAttachmentsCollectionRequest Request()
        {
            return this.Request(null);
        }

        /// <summary>
        /// Builds the request.
        /// </summary>
        /// <param name="options">The query and header options for the request.</param>
        /// <returns>The built request.</returns>
        public ITodoTaskAttachmentsCollectionRequest Request(IEnumerable<Option> options)
        {
            return new TodoTaskAttachmentsCollectionRequest(this.RequestUrl, this.Client, options);
        }

        /// <summary>
        /// Gets an <see cref="IAttachmentBaseRequestBuilder"/> for the specified TodoTaskAttachmentBase.
        /// </summary>
        /// <param name="id">The ID for the TodoTaskAttachmentBase.</param>
        /// <returns>The <see cref="IAttachmentBaseRequestBuilder"/>.</returns>
        public IAttachmentBaseRequestBuilder this[string id]
        {
            get
            {
                return new AttachmentBaseRequestBuilder(this.AppendSegmentToRequestUrl(id), this.Client);
            }
        }

        /// <summary>
        /// Gets the request builder for AttachmentBaseCreateUploadSession.
        /// </summary>
        /// <returns>The <see cref="IAttachmentBaseCreateUploadSessionRequestBuilder"/>.</returns>
        public IAttachmentBaseCreateUploadSessionRequestBuilder CreateUploadSession(
            AttachmentInfo attachmentInfo)
        {
            return new AttachmentBaseCreateUploadSessionRequestBuilder(
                this.AppendSegmentToRequestUrl("microsoft.graph.createUploadSession"),
                this.Client,
                attachmentInfo);
        }
    }
}
